#!/bin/bash

##########################################################
# Script to download a webpage using the 'wget' command  #
# Usage: ./webpagedl.sh <full webpage URL>               #
##########################################################

pagelink=$1
# Check if a URL is entered when a script is called.
if [ -z "$pagelink" ]; then
    echo "usage: ./webpagedl.sh <full webpage URL>"
    exit 1
fi

# Create a download directory in the current location.
mkdir -p webpages

# Create a filename by stripping away the trailing '/' and extracting the last part of the URL.
filename=$(echo $pagelink | sed 's:/*$::' | sed 's#.*/##')
dldir="webpages/$filename.html"

# Download the URL to the download directory.
wget -q -O "$dldir" "$pagelink"
get_exitcode=$?

# Check the exit code generated by 'wget'; if non-zero, there was an error.
if [ $get_exitcode -ne 0 ]; then
    echo "ERROR: webpagedl: the link '$pagelink' does not return a document (wget exit code $get_exitcode)" 1>&2
    exit 2
fi

# print the path to the file that was downloaded.
echo "$dldir"
